### ISSUE TITLE
Unable to login to terminal app?

### ISSUE THREAD

**Issue by abijith** [petethepig/devtools-terminal#63]
Hi, I tried to login with http://localhost, user name as admin and password empty, however the terminal app in the chrome says only "Connection Fails". Please assist.

**Comment by abijith** [comment]
Im using Yosemite, and app is connected via Native Messaging API in Chrome..please help..

**Comment by zuoRambo** [comment]
@abijith have you read the [blog](http://blog.dfilimonov.com/2013/09/12/devtools-terminal.html) ? 
1, install devtools-terminal by `npm install --loglevel verbose -g devtools-terminal` 
2, connet chrome with devtools-termianl by the command `sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl`
3, start the socket server by command `devtools-terminal`,it means the server listen 8080 in localhost
4, start the chrome and open developer-tools and click the terminal and login as `http://127.0.0.1:8080` `admin` ` ` (empty password)

**Comment by abijith** [comment]
Thanks, this works like a charm now :)
