### ISSUE TITLE
Install Success,But it doesn't work

### ISSUE THREAD

**Issue by wujunchuan** [petethepig/devtools-terminal#78]
After I install nodejs&&devtools-terminal Success,then
I execute `sudo devtools-terminal --install --id=leakmhneaibbdapdoienlkifomjceknl`

Success,return 
`Chrome Native Messaging host application installed successfully`

But Devtools Terminal doesn't work as ever...
**I try to restart Chrome over and over ,But it still doesn't work**
See below Pic
![image](https://cloud.githubusercontent.com/assets/7511631/19395361/d3df3b2c-926f-11e6-9839-ec167a4e4645.png)

**Comment by thejohnbackes** [comment]
I have a similar issue:
![image](https://cloud.githubusercontent.com/assets/13596692/20196863/821c8d02-a751-11e6-96cd-bf214176168b.png)

**Comment by thejohnbackes** [comment]
See issue #79 for the fix!
