### ISSUE TITLE
*FIX* for blank terminal

### ISSUE THREAD

**Issue by thejohnbackes** [petethepig/devtools-terminal#79]
Hi everyone. I, like many of you, had the following issue:
1. install worked. (hurray!)
2. blank terminal (oh no!)

This simple fix made it work for me:

- run devtools-terminal in the shell:
`$ devtools-terminal`
![image](https://cloud.githubusercontent.com/assets/13596692/20197595/38b7af80-a755-11e6-9f08-b20da904ecf3.png)
- open chrome devtools
- click three dots in corner
- click Remote Connection
![image](https://cloud.githubusercontent.com/assets/13596692/20197477/a737a790-a754-11e6-8af8-b3f4853f6f14.png)
host: http://localhost:8080
user: admin
password: (none)
![image](https://cloud.githubusercontent.com/assets/13596692/20197486/b0d0e276-a754-11e6-9d7a-4fec42b0c57f.png)
- click 'ok'
![image](https://cloud.githubusercontent.com/assets/13596692/20197510/d1c8b9c2-a754-11e6-8cfc-aec4f1cc4afe.png)
Voila! Command Line Magic!
#67 #71 #49 #78 #77 #75 #74 #57

**Comment by jackbackes** [comment]
I believe the root issue is found in the default example-config.js:

```
exports.config = {
  users: {
    admin: {
      password: "",
      cwd: process.cwd()
    }
  },
  port: 8080
};
```

**Comment by jackbackes** [comment]
here you see the username is admin, password is "", and port is 8080, which exactly matches the steps that must be entered for remote access.

**Comment by jackbackes** [comment]
I don't know why local access doesn't work. Perhaps @petethepig can enlighten?

**Comment by ubermensh** [comment]
no `remote connection` option in chrome 58
the three dot menu looks different

**Comment by joshmccall221** [comment]
@ubermensh, I am having issues too. macOS + Chrome 60 the three dots do nothing when clicked.
